### ISSUE TITLE
Building with Ruby 2.2.0

### ISSUE THREAD

**Issue by paradisaeidae** [ibc/EventMachine-LE#25]
MerryXmas/Hols/Break!!
Now I'm looking into this: 
/RUBY/2.2.0/bin/ruby-2.2.0 -r ./siteconf20141229-31008-i3cxa3.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling pipe.cpp
compiling cmain.cpp
compiling rubymain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp: In member function ‘bool EventMachine_t::_RunEpollOnce()’:
em.cpp:551:37: error: ‘rb_thread_select’ was not declared in this scope
em.cpp: In member function ‘int SelectData_t::_Select()’:
em.cpp:810:67: error: ‘rb_thread_select’ was not declared in this scope
em.cpp: In member function ‘bool EventMachine_t::_RunSelectOnce()’:
em.cpp:949:40: error: ‘rb_thread_select’ was not declared in this scope
make: *** [em.o] Error 1

make failed, exit code 2
------------------------------
We know there has been some excellent work done on Ruby GC with 2.2.0.
I am not familiar with the scope of rb_thread_select though.
MarkT

**Comment by paradisaeidae** [comment]
So I have some mods which fix this.
They are in a local git repo forked from ibc/EventMachine-LE
To fully test it I need to understand some stuff around --pre packaging.
I am working on a fork of a --pre gem. 
I can rake (compile) and rake test in a working copy of 1.1.7
Gem build completes. Though when installing, just copies lib and ext.
rake aborted!
In my git repo, forked I get.
Don't know how to build task 'EventMachine-LE'

**Comment by paradisaeidae** [comment]
Please see pull request.

**Comment by ibc** [comment]
I don't see any pull request.

**Comment by paradisaeidae** [comment]
Hmm... yep, it went to the parent:
https://github.com/cabo/eventmachine/pulls
Howto direct this to ibc?

**Comment by ibc** [comment]
I don't think the same PR may compile in EventMachine-LE as there have been changes since the EM fork you sent the PR to.

AFAIR Github let's you easily point your PR to another fork of the same project.

**Comment by jec** [comment]
Is this issue going to be fixed soon? It's holding up my upgrade to Ruby 2.2.

**Comment by paradisaeidae** [comment]
```
                                                                                  ‎I have a fork which works with 2.2.n.I will check it is ok in (my) github repo soon. ‎There are issues with <2.2.n compat.So has not been merged.                                                                                                                                                                                                                                                                                                                                        MarkT                                                                                                                                                                                                                 From: Jim CainSent: Saturday, 16 May 2015 04:44To: ibc/EventMachine-LEReply To: ibc/EventMachine-LECc: MarkTSubject: Re: [EventMachine-LE] Building with Ruby 2.2.0 (#25)Is this issue going to be fixed soon? It's holding up my upgrade to Ruby 2.2.
```

—Reply to this email directly or view it on GitHub.
